### ISSUE TITLE
Asked for a Matrix account

### ISSUE THREAD

**Issue by carmilso** [Stanford-Mobisocial-IoT-Lab/thingengine-platform-server#4]
After the last update, when I start the server I get the following message:

`You haven't configured a Matrix account yet. You need a Matrix account to let me talk to other Almonds.
Loaded manifest for org.thingpedia.builtin.matrix, module type: org.thingpedia.builtin, version: 1`

**Comment by gcampax** [comment]
Yeah, it should ask for your email and let you say it in voice or type it from the web interface (which is available at 127.0.0.1:3000/conversation ).
You can register the account at https://riot.im

**Comment by carmilso** [comment]
But what is this for?

**Comment by carmilso** [comment]
Okay, thanks!
