### ISSUE TITLE
Web socket closed after few seconds

### ISSUE THREAD

**Issue by carmilso** [Stanford-Mobisocial-IoT-Lab/thingengine-platform-server#5]
In the view of "conversation" the web socket is closed without doing anything after few seconds. The event of the "onclose" function is the following (and it provides any reason):

```
{
	bubbles: false
	cancelBubble: false
	cancelable: false
	code: 1006
	composed: false
	currentTarget: WebSocket {
		url: "wss://XXXX/api/conversation",
		readyState: 3,
		bufferedAmount: 0,
		onopen: null,
		onerror: null,
		…
	}
	defaultPrevented: false
	eventPhase: 0
	isTrusted: true
	path: []
	reason: ""
	returnValue: true
	srcElement: WebSocket {
		url: "wss://XXXX/api/conversation",
		readyState: 3,
		bufferedAmount: 0,
		onopen: null,
		onerror: null,
		…
	}
	target: WebSocket {
		url: "wss://XXXX/api/conversation",
		readyState: 3,
		bufferedAmount: 0,
		onopen: null,
		onerror: null,
		…
	}
	timeStamp: 60285.39500000001
	type: "close"
	wasClean: false
}
```

**Comment by gcampax** [comment]
platform-server does not do HTTPS, so the websockets should be ws:// not wss://

Other than that, is there anything logged on the server side? Maybe it's crashing?

**Comment by carmilso** [comment]
I have been doing tests and I can make It work for a while. But, eventually it crashes. In the server it only enters in the "onclose" event with an argument with value 1006 (the same as the one that can be seen in the frontend). Unfortunately in the Object received as argument in the "onclose" event in the frontend It shows no reason.

**Comment by carmilso** [comment]
It is fixed modifying increasing the timeout in the Nginx. So closing...
